i = 2
s = {1, 10, 8, 4, 6}
t = {3, 6, 9}
d = {'x': 100, 'y': 200, 'z': 300}
print('3')
print(t)
print('4')
print( sorted(d.keys()))
print('5')
print(d.get('y'))
print('6')
print(len(d))
print(type(len(d)))
print('7')
print(s&t)
print('8')
print(s-t)
print('9')
print(s|t)
print('10')
print(200 not in d)
print(type(200 not in d))
print('11')
print(t<=s)
print(type(t<=s))
print('12')
print('x' in d)
print(type('x' in d))
print('13')
print(100 in d)
print(type(100 in d))
print('14')
print(1 in s)
print(type(1 in s))